<?php
    /*
        This file was automatically generated by /etc/database/xml2dbmodule.xsl
    */
    $db_prep = "";
    $bans = $db_prep . "bans";
    $blogs = $db_prep . "blogs";
    $bookmarkfolders = $db_prep . "bookmarkfolders";
    $bookmarks = $db_prep . "bookmarks";
    $bugs = $db_prep . "bugs";
    $chatchannels = $db_prep . "chatchannels";
    $chatmsg = $db_prep . "chatmsg";
    $chatusers = $db_prep . "chatusers";
    $countries = $db_prep . "countries";
    $cronlogs = $db_prep . "cronlogs";
    $deleted_media = $db_prep . "deleted_media";
    $deletedphotoalbums = $db_prep . "deletedphotoalbums";
    $docfolders = $db_prep . "docfolders";
    $docitems = $db_prep . "docitems";
    $earth = $db_prep . "earth";
    $errorlogs = $db_prep . "errorlogs";
    $formulas = $db_prep . "formulas";
    $friendfolders = $db_prep . "friendfolders";
    $friends = $db_prep . "friends";
    $globalcomments = $db_prep . "globalcomments";
    $invitations = $db_prep . "invitations";
    $logs = $db_prep . "logs";
    $media = $db_prep . "media";
    $messagefolders = $db_prep . "messagefolders";
    $messages = $db_prep . "messages";
    $mfilters = $db_prep . "mfilters";
    $mfiltertypes = $db_prep . "mfiltertypes";
    $mfolder_user = $db_prep . "mfolder_user";
    $mrecipients = $db_prep . "mrecipients";
    $mspams = $db_prep . "mspams";
    $permissions = $db_prep . "permissions";
    $photoalbums = $db_prep . "photoalbums";
    $photoalbumsmedia = $db_prep . "photoalbumsmedia";
    $polloptions = $db_prep . "polloptions";
    $polls = $db_prep . "polls";
    $pollvotes = $db_prep . "pollvotes";
    $postcomments = $db_prep . "postcomments";
    $posts = $db_prep . "posts";
    $templates = $db_prep . "templates";
    $useravatars = $db_prep . "useravatars";
    $users = $db_prep . "users";
?>