#!/usr/bin/php
<?php
    /*
    Module: Stabilization script
    File: /modules/stabilize/configeditor.php
    Developers: ch-world
    */
    $configfile = "/var/www/vhosts/blogcube.net/conf/stable.conf";
    $basepath = "/var/www/vhosts/blogcube.net/httpdocs/";
    if( $argc != 2 && $argc != 3) {
        die( "Usage: configeditor.php <revision> [paris]\n" );
    }
    
    // read the old config file
    $handle = fopen( $configfile , "r");
    if ( !$handle ) {
        die( "Failed to open configuration file for reading\n" );
    }
    $argv[ 1 ] = 'r' . $argv[ 1 ];
    $path[ 'docroot' ] = $basepath . '_/';
    $path[ 'paris' ] = $basepath . '_/';
    while( !feof( $handle )) {
        $buffer = fgets( $handle );
        if( substr( $buffer, 1, 1 ) != "#" ) {
            // no comment, parse it
            $parts = explode( " " , $buffer );
            switch( $parts[ 0 ] ) {
                case "DocumentRoot":
                    if ( isset( $parts[ 2 ] ) ) {
                        $path[ 'docroot' ] = $parts[ 2 ];
                    }
                    break;
                case "Alias":
                    if ( isset( $parts[ 3 ] ) ) {
                        $path[ 'paris' ] = $parts[ 3 ];
                    }
                    break;
            }
        }
    }
    fclose( $handle );
    
    if( $argc == 2 ) {
        if( file_exists( $basepath . $argv[ 1 ] )) {
            $path[ 'docroot' ] = $basepath . $argv[ 1 ];
        }
        else {
            die( "Path not existing: " . $basepath . $argv[ 1 ] );
        }
    }
    elseif( $argc == 3 ) {
        if( file_exists( $basepath . $argv[ 1 ] )) {
            $path[ 'paris' ] = $basepath . $argv[ 1 ] . '/';
        }
        else {
            die( "Path not existing: " . $basepath . $argv[ 1 ] );
        }
    }
    
    // generate config file
    $content = "### DO NOT EDIT THIS FILE MANUALLY! CREATED BY BLOGCUBE STABILIZATION SCRIPT\n";
    $content .= "DocumentRoot " . $path[ 'docroot' ] . "\n";
    $content .= "Alias /paris " . $path[ 'paris' ];
    
    if( !is_writable( $configfile )) {
        die( "Can't write to config file" );
    }
    $handle = fopen( $configfile , "w");
    if ( !$handle ) {
        die( "Failed to open configuration file for writing\n" );
    }
    fwrite( $handle, $content );
    fclose( $handle );
    exec( "/usr/sbin/rcapache2 reload" );
?>